### ISSUE TITLE
セットアップ：プレイヤーの支援点の決定

### ISSUE THREAD

**Issue by qumari** [tackman/yurikure#2]
支援点を決める時点で、ゲームプレイは開始している印象があるので、
「セットアップ」の章には入れないほうが良い気がします。

セットアップとターン進行の間にあるナニカではないでしょうか？
（いいアイデアが思い浮かばないけど）

**Comment by tackman** [comment]
ゲーム中一度だけ行う内容をセットアップ、終了条件を満たすまでループするものをターン進行にまとめているので半端はブロック追加はしないでおきます
