### ISSUE TITLE
不満度5の場合、出目6でも別れてしまう

### ISSUE THREAD

**Issue by tackman** [tackman/yurikure#8]
という指摘があったけれど、そうじゃないかもしれない（要確認）
ただ、仮に誤読だったとしても誤読が発生するという問題はある模様

**Comment by qumari** [comment]
ちょっとタイトルとは異なるけど、
カップルのフェーズは
出目６は例外で優先処理（かつ「出目ー不満度」処理は行わず別れない）、なのか
出目－不満度処理後に出目６処理、なのか
ちょっと読み手に依存すると思いました。

**Comment by tackman** [comment]
より明確な文言にした＆捕捉で明記しました
